import Head from "next/head";
import Footer from "./footer";

interface CustomComp {
    children: JSX.Element | JSX.Element[];
}

const Layout = ({ children }: CustomComp) => {

    return (
        <>
            <Head>
                <title>IP Address Tracker</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-32x32.png" />
                <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossOrigin="" />
                

            </Head>
            <main className="h-screen w-screen m-0">
                <div className="">
                    {children}
                </div>
                
                <div className="absolute bottom-0">
                    <Footer />
                </div>
            </main>
        </>
    );
}

export default Layout;